### ISSUE TITLE
I apply ModelSliderCell in UITableView. It didn't works

### ISSUE THREAD

**Issue by oddukgi** [oklemenz/OKit#1]
Hello! thank you making good api.
I applied uislider on tableview. 
I can't move slider.
I made code like this. 

```swift
 func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: self.reuseIdetifier[1]) as? ModelSliderCell else {
            fatalError("failed to create a new cell")
        }
        cell.valuePath  = "percent"
        cell.minValuePath = "#0"
        cell.maxValuePath = "#100"
        cell.path = "%Percent: ,percent, %%"
        return cell
    }
```

<img width="226" alt="slider" src="https://user-images.githubusercontent.com/3068049/89532381-a82e7900-d82c-11ea-908c-a7f8f969db54.png">

**Comment by oklemenz** [comment]
OKit prefers the usage of storyboards to enabled Model Cells. Because then setting the context binding is done under the hood by the model list view controller. You can have a look at the following reference example, where also a slider control is included. This project should get you started, how to use Okit:
https://github.com/oklemenz/OKit/tree/master/Examples/Bookshop
